# Generated by Django 4.1.5 on 2023-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otkyda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('names', models.CharField(max_length=10)),
                ('data_tyda', models.DateField()),
                ('data_otyda', models.DateField()),
                ('pas', models.IntegerField()),
            ],
        ),
    ]
