# Generated by Django 4.1.5 on 2023-03-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkyda',
            name='pas',
            field=models.IntegerField(max_length=5),
        ),
    ]
